apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: edgenode-agent
  namespace: default
spec:
  selector:
    matchLabels:
      app: edgenode-agent
  template:
    metadata:
      labels:
        app: edgenode-agent
    spec:
      serviceAccountName: edgenode-agent-sa
      containers:
        - name: agent
          image: tuusuario/agent-node-status:latest # Reemplaza con tu imagen real
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            limits:
              cpu: "100m"
              memory: "50Mi"
            requests:
              cpu: "50m"
              memory: "25Mi"
      tolerations:
        - effect: NoSchedule
          operator: Exists
      restartPolicy: Always
